import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { ClientTan } from "@/components/CliendTan";

export const metadata: Metadata = {
  title: "Tando X oM",
  description: "Generated by create next app",
  icons : {
    icon : "/First.jpg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ClientTan>
    <html lang="en">
      <body> 
      <div>
      <Navbar/>
      <main>
        {children}
        </main>
      </div>
      </body>
    </html>
    </ClientTan>
    </ClerkProvider>
  );
}
